name: "Resume Actions"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Run full code checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Setup Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "yarn"
      - name: Run Checks
        run: |
          yarn install
          yarn check:full

  dependency-review:
    name: Dependency Review
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Dependency Review
        uses: actions/dependency-review-action@v5
        continue-on-error: true
